version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - gocyclo
    - misspell
    - nolintlint

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
