# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux
      - CXX=zig c++ -target x86_64-linux
    goos:
      - linux
    goarch:
      - amd64
    main: .
    binary: igor-php
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux
      - CXX=zig c++ -target aarch64-linux
    goos:
      - linux
    goarch:
      - arm64
    main: .
    binary: igor-php
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows
      - CXX=zig c++ -target x86_64-windows
    goos:
      - windows
    goarch:
      - amd64
    main: .
    binary: igor-php
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge"
