services:
  php:
    image: dunglas/frankenphp
    ports:
      - "8080:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - SERVER_NAME=:80
      - FRANKENPHP_CONFIG=worker ./public/index.php 1
      - APP_ENV=dev
      - APP_SECRET=igor_secret
    volumes:
      - ../../:/app
    working_dir: /app/examples/demo-leak-symfony
    tty: true
